[tool.poetry]
name = "nzshm_common"
version = "0.3.1"
description = "A small pure python library for shared NZ NSHM data like locations."
authors = ["Chris Chamberlain <chrisbc@artisan.co.nz>"]
license = "GNU Affero V3"

packages = [
	{ include = "nzshm_common" },
	{ include = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0.0"
geopandas = {version = "^0.11.1", optional = true, extras = ["geometry"]}
Shapely = {version = "^1.8.3", optional = true, extras = ["geometry"]}

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"
isort = "^5.10.1"

flake8  = { version = "^3.9.2"}
flake8-docstrings = { version = "^1.6.0", optional = true }
mypy = {version = "^0.900"}

pytest-cov  = { version = "^2.12.0"}
tox = { version = "^3.20.1"}
virtualenv  = { version = "^20.2.2", optional = true}
pip  = { version = "^20.3.1", optional = true}

[tool.poetry.extras]

geometry = ["geopandas"]

test = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "flake8",
    "flake8-docstrings",
    "pytest-cov"
    ]

dev = ["tox", "pre-commit", "virtualenv", "pip", "twine", "toml", "bump2version"]

[tool.poetry.group.dev.dependencies]
Shapely = "^1.8.3"

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py38', 'py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_gitignore = true

[build-system]
requires = ["poetry-core>=1.1.0b3"]
build-backend = "poetry.core.masonry.api"
