[tool.poetry]
name = "nzshm_common"
version = "1.1.0"
description = "A small pure python library for shared NZ NSHM data like locations."
authors = ["Chris Chamberlain <chrisbc@artisan.co.nz>"]
license = "GNU Affero V3"

packages = [
	{ include = "nzshm_common" },
	{ include = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.7.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
